### ISSUE TITLE
Add a .gitignore file

### ISSUE THREAD

**Issue by kilasuit** [AdminTurnedDevOps/PwshDocker#5]
`.gitignore` files allow you to specify files or directories that aren't then scanned by git for changes and help in reducing sharing of build artifacts

For more info on `.gitignore` please see https://git-scm.com/docs/gitignore

**Comment by AdminTurnedDevOps** [comment]
Thanks! The reason why I didn't have one in is that I wasn't ignoring anything specific. From a build and artifact perspective, the repository is pretty clean. I took out the .NET binaries that I had in, so there shouldn't be any versioning issues on that front.
